name: .NET Framework Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore NuGet dependencies
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet restore UnitTests/UnitTests.csproj --configfile nuget.config

      - name: Build the solution
        run: msbuild UnitTests/UnitTests.csproj -property:Configuration=Debug

      - name: List build output
        run: |
          dir UnitTests/bin/Debug

      - name: Run tests
        run: dotnet vstest UnitTests/bin/Debug/UnitTests.dll
