name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add NuGet private feed
        run: nuget sources Add -Name "GitHubPackages" -Source "https://nuget.pkg.github.com/rdok/index.json" -Username "rdok" -Password "${{ secrets.NUGET_API_KEY }}"

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: msbuild -t:build -restore -p:RestorePackagesConfig=true -p:Configuration=Debug CustomMusic.sln

      - name: Run NUnit Tests
        run: |
          & "packages/NUnit.ConsoleRunner.3.18.1/tools/nunit3-console.exe" UnitTests/bin/Debug/UnitTests.dll
