name: .NET Framework Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet dependencies for UnitTests project
        run: dotnet restore UnitTests/UnitTests.csproj --locked-mode

      - name: Build the UnitTests project
        run: msbuild UnitTests/UnitTests.csproj -t:rebuild -property:Configuration=Debug -verbosity:minimal

      - name: List build output
        run: |
          dir UnitTests/bin/Debug

      - name: Run tests
        run: dotnet vstest UnitTests/bin/Debug/UnitTests.dll
