name: .NET Framework Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Add NuGet private feed
        run: nuget sources Add -Name "GitHubPackages" -Source "https://nuget.pkg.github.com/rdok/index.json" -Username "rdok" -Password "${{ secrets.NUGET_API_KEY }}"

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build UnitTests project
        run: msbuild CustomMusic.sln /restore /t:UnitTests /p:Configuration="Debug" /p:Platform="AnyCPU"

      - name: List build output
        run: |
          dir UnitTests/bin/Debug

      - name: Run tests
        run: dotnet vstest UnitTests/bin/Debug/UnitTests.dll
