name: .NET Framework Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore NuGet dependencies in locked mode
        run: dotnet restore --locked-mode

      - name: Build the project
        run: msbuild UnitTests/UnitTests.csproj /p:Configuration=Debug /p:CI_BUILD=true

      - name: List build output
        run: |
          dir UnitTests/bin/Debug

      - name: Run tests
        run: |
          dotnet vstest UnitTests/bin/Debug/UnitTests.dll
